
# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build senator unicorne'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["boardsource/unicorne"]'
      alphas: '["colemak"]'
      clipboard: '["win"]'
      merge: '["qmk/qmk_firmware/master"]'
